# Generated by Django 2.2.1 on 2019-05-31 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Challenges', 'verbose_name_plural': 'Challenge'},
        ),
    ]
