# Generated by Django 2.2.1 on 2019-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20190531_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
    ]
