# Generated by Django 2.2.1 on 2019-05-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20190531_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
